"""
Deterministic enumeration (r1 route): find 20-point no-three-in-line
configurations on a 10x10 grid that are invariant under the
point-symmetry group Z/2 generated by the 180-degree rotation

    sigma : (r, c)  ->  (9 - r, 9 - c).

A sigma-invariant 20-point set is the union of 10 orbits, each of
size 2 (the grid has no fixed points under sigma because 9 is odd).
An orbit is determined by picking one representative (r, c) with
(r, c) < sigma(r, c) in lexicographic order — i.e., r < 5, or r == 5
is impossible (there is no center row on a 10x10 grid), so we take
r in {0,1,2,3,4} freely and r = 4 constrains c < 5 up to tie-break.

Algorithm:
  1. Enumerate half-plane representatives H = {(r, c) : r < 5} (50 cells).
  2. Backtrack on subsets of H of size 10: each selected representative
     contributes itself and sigma(representative).
  3. Collinearity check incrementally as points are added.
  4. Return the first (or all) 10-element H-subsets whose full
     sigma-orbit union has no three collinear.

Second route: same but with the 4-fold symmetry group generated by

    tau : (r, c)  ->  (c, 9 - r)      (90-degree rotation)

so orbits have size 4 and we only need 5 representatives to span 20
points. Fewer degrees of freedom, faster search.

NO randomness. NO scipy. NO sklearn. Pure combinatorial backtracking.
"""

from itertools import combinations


N = 10


def cross(o, a, b):
    return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])


def sigma(p):
    """180-degree rotation of the 10x10 grid about its center."""
    return (N - 1 - p[0], N - 1 - p[1])


def tau(p):
    """90-degree rotation of the 10x10 grid about its center (clockwise)."""
    return (p[1], N - 1 - p[0])


def orbit_under_sigma(p):
    q = sigma(p)
    if p == q:
        return (p,)
    return (p, q)


def orbit_under_tau(p):
    out = [p]
    q = tau(p)
    while q != p:
        out.append(q)
        q = tau(q)
    return tuple(out)


def no_three_collinear(points):
    pts = list(points)
    n = len(pts)
    for i in range(n):
        oi = pts[i]
        for j in range(i + 1, n):
            aj = pts[j]
            dx = aj[0] - oi[0]
            dy = aj[1] - oi[1]
            for k in range(j + 1, n):
                bk = pts[k]
                if dx * (bk[1] - oi[1]) - dy * (bk[0] - oi[0]) == 0:
                    return False
    return True


def backtrack_sigma(target_size=20, limit_solutions=1, verbose=False):
    """Find sigma-invariant no-3-collinear sets of size target_size.

    Representatives: all 50 cells with r < 5.
    Picking K of them produces 2K points (sigma pairs them up).
    For target_size = 20 we need K = 10 representatives.
    """
    assert target_size % 2 == 0
    K = target_size // 2

    # Canonical representatives with lexicographic order.
    reps = [(r, c) for r in range(N // 2) for c in range(N)]
    assert len(reps) == 50
    # Pre-compute sigma(rep) for each rep.
    sig = [sigma(r) for r in reps]

    solutions = []
    chosen = []
    chosen_pts = []

    def recurse(start):
        if len(chosen) == K:
            if no_three_collinear(chosen_pts):
                solutions.append(list(chosen_pts))
                if verbose:
                    print(f"FOUND solution with {len(chosen_pts)} pts: {chosen_pts}")
            return len(solutions) >= limit_solutions
        # Bound: need K - len(chosen) more reps from reps[start:].
        remaining_slots = K - len(chosen)
        for idx in range(start, len(reps) - remaining_slots + 1):
            p = reps[idx]
            q = sig[idx]
            # Cheap pre-check: does adding {p, q} keep no-3-collinear?
            candidate = chosen_pts + [p, q]
            # Only check triples involving at least one of {p, q}.
            ok = True
            # Check triple (p, q, any old) and (any two old, p or q).
            # Since adding 2 points at once we must check all triples
            # in candidate that include p or q.
            old = chosen_pts
            n_old = len(old)
            # Triple (a, b, p) for a,b in old
            for a in range(n_old):
                if not ok:
                    break
                oa = old[a]
                for b in range(a + 1, n_old):
                    ob = old[b]
                    if cross(oa, ob, p) == 0:
                        ok = False
                        break
                    if cross(oa, ob, q) == 0:
                        ok = False
                        break
            # Triple (a, p, q) for a in old
            if ok:
                for a in range(n_old):
                    if cross(p, q, old[a]) == 0:
                        ok = False
                        break
            if not ok:
                continue
            chosen.append(idx)
            chosen_pts.extend([p, q])
            done = recurse(idx + 1)
            chosen_pts.pop()
            chosen_pts.pop()
            chosen.pop()
            if done:
                return True
        return False

    recurse(0)
    return solutions


def backtrack_tau(target_size=20, limit_solutions=1, verbose=False):
    """Find tau-invariant (4-fold rotation) no-3-collinear sets.

    The 90-degree rotation tau acts on the 10x10 grid with orbits
    exclusively of size 4 (no fixed points, no size-2 orbits since
    tau^2 = sigma has no fixed points either). For target_size = 20
    we need 5 orbit-representatives.

    Canonical representatives: one per tau-orbit.
    """
    assert target_size % 4 == 0
    K = target_size // 4

    seen_orbit = set()
    reps = []
    orbit_of = []
    for r in range(N):
        for c in range(N):
            p = (r, c)
            if p in seen_orbit:
                continue
            o = orbit_under_tau(p)
            if len(o) != 4:
                continue  # only size-4 orbits
            for q in o:
                seen_orbit.add(q)
            reps.append(p)
            orbit_of.append(o)

    if verbose:
        print(f"#tau reps: {len(reps)} (each orbit size 4)")

    solutions = []
    chosen_pts = []

    def recurse(start):
        if len(chosen_pts) == target_size:
            if no_three_collinear(chosen_pts):
                solutions.append(list(chosen_pts))
            return len(solutions) >= limit_solutions
        remaining_reps_needed = K - len(chosen_pts) // 4
        for idx in range(start, len(reps) - remaining_reps_needed + 1):
            orb = orbit_of[idx]
            # Check triples involving any of the 4 new points.
            old = chosen_pts
            new = orb
            ok = True
            # triples (old, old, new_i)
            for i in range(len(old)):
                if not ok:
                    break
                oa = old[i]
                for j in range(i + 1, len(old)):
                    if not ok:
                        break
                    ob = old[j]
                    for n_ in new:
                        if cross(oa, ob, n_) == 0:
                            ok = False
                            break
            # triples (old, new_i, new_j)
            if ok:
                for i_ in range(len(new)):
                    for j_ in range(i_ + 1, len(new)):
                        if not ok:
                            break
                        for oa in old:
                            if cross(new[i_], new[j_], oa) == 0:
                                ok = False
                                break
                    if not ok:
                        break
            # triples (new_i, new_j, new_k)
            if ok:
                for i_ in range(len(new)):
                    for j_ in range(i_ + 1, len(new)):
                        if not ok:
                            break
                        for k_ in range(j_ + 1, len(new)):
                            if cross(new[i_], new[j_], new[k_]) == 0:
                                ok = False
                                break
            if not ok:
                continue
            chosen_pts.extend(new)
            done = recurse(idx + 1)
            for _ in range(4):
                chosen_pts.pop()
            if done:
                return True
        return False

    recurse(0)
    return solutions


def backtrack_klein4(target_size=20, limit_solutions=1, verbose=False):
    """Find Klein-4 (D2 = <sigma_h, sigma_v>) invariant sets.

    Horizontal flip h: (r, c) -> (r, 9 - c).
    Vertical   flip v: (r, c) -> (9 - r, c).
    Group = {e, h, v, sigma = h v}. Orbits have size 4 (no fixed pts).
    For target 20 we need 5 orbit representatives.

    This is the "doubly-symmetric half-plane enumeration" of the
    replica spec — pick a quarter-plane rep, its orbit fills the rest.
    """
    assert target_size % 4 == 0
    K = target_size // 4

    def orbit_k4(p):
        r, c = p
        return ((r, c), (r, N - 1 - c), (N - 1 - r, c), (N - 1 - r, N - 1 - c))

    # Representatives: cells in the upper-left quarter (r<5, c<5).
    seen = set()
    reps = []
    orbit_of = []
    for r in range(N // 2):
        for c in range(N // 2):
            p = (r, c)
            if p in seen:
                continue
            o = orbit_k4(p)
            if len(set(o)) != 4:
                continue
            for q in o:
                seen.add(q)
            reps.append(p)
            orbit_of.append(o)

    if verbose:
        print(f"#klein4 reps: {len(reps)}")

    solutions = []
    chosen_pts = []

    def recurse(start):
        if len(chosen_pts) == target_size:
            if no_three_collinear(chosen_pts):
                solutions.append(list(chosen_pts))
            return len(solutions) >= limit_solutions
        remaining_reps_needed = K - len(chosen_pts) // 4
        for idx in range(start, len(reps) - remaining_reps_needed + 1):
            orb = orbit_of[idx]
            old = chosen_pts
            new = orb
            ok = True
            for i in range(len(old)):
                if not ok:
                    break
                oa = old[i]
                for j in range(i + 1, len(old)):
                    if not ok:
                        break
                    ob = old[j]
                    for n_ in new:
                        if cross(oa, ob, n_) == 0:
                            ok = False
                            break
            if ok:
                for i_ in range(len(new)):
                    for j_ in range(i_ + 1, len(new)):
                        if not ok:
                            break
                        for oa in old:
                            if cross(new[i_], new[j_], oa) == 0:
                                ok = False
                                break
                    if not ok:
                        break
            if ok:
                for i_ in range(len(new)):
                    for j_ in range(i_ + 1, len(new)):
                        if not ok:
                            break
                        for k_ in range(j_ + 1, len(new)):
                            if cross(new[i_], new[j_], new[k_]) == 0:
                                ok = False
                                break
            if not ok:
                continue
            chosen_pts.extend(new)
            done = recurse(idx + 1)
            for _ in range(4):
                chosen_pts.pop()
            if done:
                return True
        return False

    recurse(0)
    return solutions


if __name__ == "__main__":
    import time

    print("=== sigma (180-deg rotation), size 20 = 10 reps of orbit size 2 ===")
    t0 = time.time()
    sols = backtrack_sigma(target_size=20, limit_solutions=1, verbose=True)
    t1 = time.time()
    print(f"sigma search done in {t1 - t0:.2f}s, solutions={len(sols)}")
    if sols:
        print("First sigma-invariant 20-pt solution:")
        for p in sorted(sols[0]):
            print("  ", p)
