# Auto-generated by solution_generator.py — do not edit by hand.
# Orbit: 01-algebraic-local-search
# Points: 20 (target = 20)

N = 10
POINTS = [
    (3, 2),
    (8, 5),
    (9, 1),
    (9, 0),
    (7, 8),
    (1, 3),
    (6, 8),
    (5, 9),
    (5, 3),
    (8, 0),
    (0, 6),
    (2, 5),
    (3, 9),
    (4, 1),
    (6, 4),
    (1, 2),
    (7, 6),
    (2, 7),
    (0, 4),
    (4, 7),
]
