"""
Orbit 02 — deterministic closed-form 20-point no-three-in-line on 10×10.

Extends orbit/01-algebraic-local-search.r1 by REPLACING its
randomized hill-climb with a fully deterministic construction:

    (1) partition the 10 columns {0..9} into 5 disjoint unordered pairs,
    (2) assign each pair to one upper-half row r in {0..4},
    (3) complete by mirror symmetry  (r, c)  ↔  (9-r, 9-c).

Iteration is done in strict lexicographic order (no `random.*` calls
anywhere) via `constructor.sweep_doubly_symmetric()`; on this code path
the FIRST assignment tried that survives the no-three-collinear
predicate is committed as POINTS.

Provenance (re-derivable by running `python3 constructor.py` from this
directory) — verified by also checking the points are mirror-symmetric
under (r,c) → (9-r, 9-c) and have exactly 2 per row / 2 per column.

References:
  - Dudeney, H. E. (1917). Amusements in Mathematics. Puzzle 317.
  - Erdős, P. (1951). On a problem of Dudeney. MAA Monthly 58.
  - Flammenkamp, A. (1998). Progress on the no-three-in-line problem, II.
    J. Combin. Theory A 81, 108-113. — Lists doubly-symmetric 20-point
    solutions for n=10. The configuration below has the same symmetry
    group (Z/2 generated by central inversion) as Flammenkamp's family.
"""

N = 10

# Output of `constructor.sweep_doubly_symmetric()` — the first
# lexicographically-ordered 10-column partition + row assignment whose
# mirror completion is no-three-collinear.  See constructor.py and
# construction_proof.md for the deterministic derivation and proof of
# validity (no call to `random` anywhere in the chain).
POINTS = [
    (0, 2), (0, 3),
    (1, 6), (1, 7),
    (2, 0), (2, 1),
    (3, 8), (3, 9),
    (4, 4), (4, 5),
    (5, 4), (5, 5),
    (6, 0), (6, 1),
    (7, 8), (7, 9),
    (8, 2), (8, 3),
    (9, 6), (9, 7),
]


if __name__ == "__main__":
    # Local self-test.
    assert len(POINTS) == 20 and len(set(POINTS)) == 20
    assert all(0 <= r < N and 0 <= c < N for (r, c) in POINTS)
    # Mirror symmetry  (r, c)  ↔  (9-r, 9-c).
    S = set(POINTS)
    assert all((9 - r, 9 - c) in S for (r, c) in POINTS)
    # No three collinear (integer cross product).
    def cross(o, a, b):
        return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])
    for i in range(20):
        for j in range(i + 1, 20):
            for k in range(j + 1, 20):
                assert cross(POINTS[i], POINTS[j], POINTS[k]) != 0, (
                    f"collinear: {POINTS[i]}, {POINTS[j]}, {POINTS[k]}"
                )
    print(f"OK: {len(POINTS)} points, deterministic closed-form, no three collinear.")
